- lib/default.nix
...in inputs of the users flake.
Without this, the examples in README.md and templates don't work for me as the miss this input. (nix 2.18.2)
> Use systems from blueprint, if not specified

- templates/default/flake.nix
Input URL specified in the flake template should reference the authoritative GitHub repository.
> fix: Flake template input references github repo.

- README.md
- docs/folder-structure.md
- flake.nix
- formatter.nix
- lib/default.nix
- package.nix
- templates/default/flake.nix
For very simple flakes, it doesn't make sense to create a whole folder
structure.
ADDITIONS:
* Add a top-level package.nix that maps to `packages.<system>.default`
* Add a top-level formatter.nix that maps to `formatter.<system>` and `packages.<system>.formatter`.
* Load devshells from the devshells/ folder.
CHANGES:
* perSystem values now merge legacyPackages and packages in that order.
* packages are loaded with `callPackage`.
BREAKING:
* Remove `packages/<pname>/package.nix` as it makes the interface too
complicated.
* lib/default.nix: take `{ flake, inputs }:` instead of `inputs`.
> top-level refactor 

- lib/default.nix
- package.nix
It was merging on the systems level, and since Nix doesn't do a deep merge, it causes the last entry to win.
> fix: fix the merge logic in the packages

- docs/folder-structure.md
- lib/default.nix
Wrap the host configurations in one layer of indirection, so they only get evaluated when needed.
Fixes #2
@brianmcgee this is a breaking change for the `hosts/<hostname>/default.nix`
> break(hosts): eval the host configs lazily

- lib/default.nix
There was a duplicate `/default.nix` suffix which was breaking the import.
Signed-off-by: Brian McGee <brian@bmcgee.ie>
> fix: hosts fallback

- docs/folder-structure.md
- lib/default.nix
Make it more regular by also providing the perSystem argument to the
NixOS and Darwin modules.
> feat: add perSystem argument to NixOS and Darwin

- templates/default/.envrc
- templates/default/.gitignore
- templates/default/devshell.nix
- templates/default/flake.lock
Some minimal default to get start with blueprint + direnv with:
nix flake init --template numtide/blueprint
> feat(template): add a devshell to the default template

- docs/folder-structure.md
- lib/default.nix
Fixes the issue mentioned in https://github.com/numtide/blueprint/issues/33 by picking up all directories in src + /modules as modules.
Follow-up to https://github.com/numtide/blueprint/pull/34
> feat: pick up all modules in modules/ dir

- lib/default.nix
...at least in nix 2.18 and lix.
Fixes main branch, which is broken since https://github.com/numtide/blueprint/pull/40
> fix: filterAttrs is not a builtin

- lib/default.nix
If a package did not declare a `meta` field, commands such as `nix flake check` would fail due to `filterPlatforms` attempting
to read non-existent attributes. We now traverse the path with `hasAttrByPath` in order to avoid the assumption of attributes existing.
> fix: better handling of meta.platforms

- docs/folder-structure.md
Is there a better way to do this?
Either way, I think this is missing from the docs.
> add documentation about using packages in hosts

- docs/folder-structure.md
- lib/default.nix
Useful for NixOS tests and other cross-package checks.
> add checks/ folder

- formatter.nix
- lib/default.nix
This is now possible thanks to <https://github.com/NixOS/nix/pull/11438>
In older versions of Nix, "." is still passed as a default argument.
> formatter: default to format the whole project

- docs/folder-structure.md
- lib/default.nix
> Get flake, inputs, perSystem module args from publishing flake

- lib/default.nix
prior to this the values in the checks attrs weren't derivations.
---
~~marking as a draft as i'm still encountering an infinite recursion trying to use this.~~ 
the infinite recursion that i encountered is due to an intrinsic property of the module system, i.e. it's expected albeit not intuitive behavior. more in #56
> fix(lib/checks): import path of each check

- docs/folder-structure.md
- lib/default.nix
Adds support for Home Manager configurations to Blueprint, both standalone and as a system configuration module.
Related to #36
Closes #35, closes #45
The idea is that Home Manager configurations are defined per-host, as opposed to per-user. This gives users the most flexibility: instead of being tied to a single configuration per username, users can choose to either define a totally unique configuration for a particular host, or use a module to define most of the common configuration and apply light changes on top of it.
The following import paths are supported:
- `hosts/{hostname}/users/{username}.nix`
- `hosts/{hostname}/users/{username}/home-configuration.nix`
For hosts containing a system configuration, the Home Manager module and any users defined for that host will be automatically …
> feat: standalone Home Manager configurations per host

- lib/default.nix
Thinking about this because of #36 
Maybe it's best if the error message provides a link to the docs, so the solution can be fully explained.
> nix-darwin: provide a better error message when missing

- lib/default.nix
#57 introduced a subtle typo: darwinModules was changed to nixosModules. Easy to miss!
> fix: resolve broken nix-darwin configurations

- docs/folder-structure.md
- lib/default.nix
> drop perSystem from publisherArgs

- lib/default.nix
- templates/default/flake.nix
If a `description` is included in the flake, the description will be used as the template description. This makes the descriptions more meaningful without having to introduce an additional point of configuration.
> feat: populate template description using flake

- lib/default.nix
In #54, the value of `home.homeDirectory` was set based on the username from the file path. By making the module that sets this value a function, it can be based on the final `home.username` value, meaning changing the username works as expected without an additional gotcha.
> feat: set home.homeDirectory based on final username

- docs/folder-structure.md
- lib/default.nix
- templates/nixos-and-darwin-shared-homes/README.md
- templates/nixos-and-darwin-shared-homes/flake.nix
- templates/nixos-and-darwin-shared-homes/hosts/my-darwin/darwin-configuration.nix
- templates/nixos-and-darwin-shared-homes/hosts/my-darwin/users/me/home-configuration.nix
- templates/nixos-and-darwin-shared-homes/hosts/my-nixos/configuration.nix
- templates/nixos-and-darwin-shared-homes/hosts/my-nixos/users/me/home-configuration.nix
- templates/nixos-and-darwin-shared-homes/modules/home/home-shared.nix
- templates/nixos-and-darwin-shared-homes/modules/nixos/host-shared.nix
This also serves as CI test for checking that blueprint correctly integrates home-manager, nixos and nix-darwin configurations.
A new feature is also tested: on host nested home-configurations you can now access `hostConfig` which provides a way to enable things on home-managed environment based on the host system-wide config.
> Add example template on how to reuse nixos and home-manager modules.

- docs/folder-structure.md
- lib/default.nix
- templates/nixos-and-darwin-shared-homes/hosts/my-darwin/users/me/home-configuration.nix
- templates/nixos-and-darwin-shared-homes/modules/home/home-shared.nix
`hostConfig` was introduced in #85, however as pointed out by @JumpIn-Git, home-manager already provides the same functionality via the `osConfig` module argument.
This PR removes `hostConfig`.
Also added a bit of documentation about the sharing-modules example.
> Remove `hostConfig` in homes specialArgs.

- docs/folder-structure.md
- lib/default.nix
- templates/toml-devenvs/checks/bye-devshell.nix
- templates/toml-devenvs/checks/default-devshell.nix
- templates/toml-devenvs/devshell.toml
- templates/toml-devenvs/devshells/bye.nix
- templates/toml-devenvs/devshells/bye.toml
- templates/toml-devenvs/devshells/hello.toml
- templates/toml-devenvs/flake.nix
- templates/toml-devenvs/packages/bye.nix
This changeset loads TOML devshells using `numtide/blueprint`.
The only requirement is that the user's flake has an `input.devshell` otherwise they will be told to add it.
I still have to add documentation for this feature.
Basically, if you have any `/devshells/*.toml` or `/devshell.toml` they will be loaded with something like `devshell.fromTOML` but that allows custom nix modules to also access packages from `perSystem.self`. 
I'm using this branch at my local nixos setup, see https://github.com/vic/vix/tree/main/devshells for some devshells I've defined, particularly `nixos.toml` that imports `nixos/leader.nix` which can access packages defined in the flake itself.
The old behaviour is still preserved, and any `.nix` files will still be loaded as-is. So those nix files are responsible …
> feat: Load TOML shells with numtide/devshell

- lib/default.nix
Before this fix, `pkgs` was reevaluated in NixOS configurations. If any `nixpkgs.config` or `nixpkgs.overlays` was set, it got lost. Besides, this caused a performance penalty.
Besides, it was impossible to redefine `nixpkgs.pkgs` downstream because `perSystemModule` depended on `pkgs`. Any redefinition caused an infinite loop. Now it depends on `nixpkgs.hostPlatform`, which must be set in each machine configuration, so the loop is gone.
@moduon MT-9339
> fix: don't reevaluate nixpkgs in nixosConfigurations

- lib/default.nix
This is an adaption of commit f1dc2cd9ffc514a3e647b88ac11b189a11cc8144
without setting `nixpkgs.pkgs`.
By leaning on nixpkgs.hostPlatform, we allow the user to set
`nixpkgs.pkgs` themselves without breaking the evaluation.
We assume that every NixOS and other instances have this variable set.
> Set perSystem using `nixpkgs.hostPlatform` instead of `pkgs.system`

- docs/folder-structure.md
- lib/default.nix
This aims to provide the features asked for in #96 with two notable differences:
- we don't set any nixos options but empower users to do so by passing the hostname along
- we do so for nix-darwin and system-manager systems as well.
docs are updated to reflect the change.
cc @yajo
> pass file-system-derived hostname to host configurations

- templates/home-manager-standalone/flake.nix
- templates/home-manager-standalone/hosts/myhost/users/me.nix
It is related to https://github.com/numtide/blueprint/issues/102
This example is minimal flakes to check standalone home-manager.
```sh
home-manager switch --flake .
```
Because standalone home-manager and modular home-manager have different configuration parameters, you need to ensure that blueprint works correctly.
> add a minimal example for standalone home-manager.

- lib/default.nix
First commit ensures that we only get an output per package on platforms that package supports.
~nix flake check does check all packages by default, so the `pkg-*` might be regarded as duplicates. On the other hand, they don't show up in the checks output, which probably means CI would skip them with buildbot-nix et al. :/~
~Shall we just drop the second commit and evaluate them twice?~
> filter packages by platform

- lib/default.nix
Now that 25.05 was released the custom formatter can be dropped
> Replace custom formatter with nixfmt-tree

- docs/content/getting-started/configuration.md
previous typo: `<kernel>-<arch>`
updated: `<arch>-<kernel>`
> typo: docs system string syntax flipped in config.systems type
